// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WestWindSystem.Entities;

[Index("CategoryID", Name = "CategoriesProducts")]
[Index("CategoryID", Name = "CategoryID")]
[Index("ProductName", Name = "ProductName")]
[Index("SupplierID", Name = "SupplierID")]
[Index("SupplierID", Name = "SuppliersProducts")]
public partial class Product
{
    [Key]
    public int ProductID { get; set; }

    [Required(ErrorMessage = "Product name is required")]
    [StringLength(40, MinimumLength = 1, ErrorMessage = "Product name is limited to 40 characters")]
    public string ProductName { get; set; }

    public int SupplierID { get; set; }

    public int CategoryID { get; set; }

    [Required(ErrorMessage = "Quanity per Unit is required")]
    [StringLength(20, MinimumLength = 1, ErrorMessage = "Quanity per Unit is limited to 20 characters")]
    public string QuantityPerUnit { get; set; }

    [Range(0, Int16.MaxValue, ErrorMessage = "Minimum order quantity cannot be a negative amount.")]
    public short? MinimumOrderQuantity { get; set; }

    [Column(TypeName = "money")]
    [Range(0.00,double.MaxValue,ErrorMessage ="Unit price cannot be a negative amount.")]
    public decimal UnitPrice { get; set; }

    [Range(0, int.MaxValue, ErrorMessage = "Units on order cannot be a negative amount.")]
    public int UnitsOnOrder { get; set; }

    public bool Discontinued { get; set; }

    [ForeignKey("CategoryID")]
    [InverseProperty("Products")]
    public virtual Category Category { get; set; }

    [InverseProperty("Product")]
    public virtual ICollection<ManifestItem> ManifestItems { get; set; } = new List<ManifestItem>();

    [InverseProperty("Product")]
    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();

    [ForeignKey("SupplierID")]
    [InverseProperty("Products")]
    public virtual Supplier Supplier { get; set; }
}